#!/usr/bin/env bash
set -e

echo Installing madcli...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
MADUP_DIR=${MADUP_DIR-"$BASE_DIR/.madup"}
MADUP_BIN_DIR="$MADUP_DIR/bin"
MADUP_MAN_DIR="$MADUP_DIR/share/man/man1"

BIN_URL="https://github.com/Generative-Labs/Madara-AppChain-CLI/releases/latest/download/madcli-$(uname -s | awk '{ print tolower($0) }')-x64"
MADARA_GENESIS_BIN_URL="https://github.com/Generative-Labs/Madara-AppChain-CLI/releases/latest/download/madara-genesis-modifier-$(uname -s | awk '{ print tolower($0) }')-x64"

# Create the .madup bin directory and madup binary if it doesn't exist.
mkdir -p $MADUP_BIN_DIR

BIN_PATH="$MADUP_BIN_DIR/madcli"

curl -H 'Pragma: no-cache' -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# download appchain_genesis.json
APPCHAIN_GENESIS_PATH="$MADUP_BIN_DIR/appchain_genesis.json"
APPCHAIN_GENESIS_URL="https://raw.githubusercontent.com/Generative-Labs/Madara-AppChain-CLI/main/madcliup/appchain_genesis.json"

curl -H 'Pragma: no-cache' -L $APPCHAIN_GENESIS_URL -o $APPCHAIN_GENESIS_PATH

# genesis-modifier
echo Installing madara-genesis-modifier...

MADARA_GENESIS_PATH="$MADUP_BIN_DIR/madara-genesis-modifier"

curl -H 'Pragma: no-cache' -L $MADARA_GENESIS_BIN_URL -o $MADARA_GENESIS_PATH
chmod +x $MADARA_GENESIS_PATH

# Create the man directory for future man files if it doesn't exist.
mkdir -p $MADUP_MAN_DIR

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "madcli: could not detect shell, manually add ${MADUP_BIN_DIR} to your PATH."
    exit 1
esac

source ${PROFILE}

# Only add madup if it isn't already in PATH.
if [[ ":$PATH:" != *":${MADUP_BIN_DIR}:"* ]]; then
    # Add the madup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$MADUP_BIN_DIR\"" >> $PROFILE

    source ${PROFILE}
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added madup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use madcli."
echo "Then, simply run 'madcli' to use Madcli."
